### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by DmitryHordyna** [DmitryHordyna/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Hordyna-Dmytro** [comment]
братам сам думай

**Comment by Hordyna-Dmytro** [comment]
реопен

**Comment by DmitryHordyna** [comment]
дякую
