### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by DmitryHordyna** [DmitryHordyna/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Hordyna-Dmytro** [comment]
прийдеться попотіти дядька

**Comment by Hordyna-Dmytro** [comment]
ой .дядька соррі закрив

**Comment by DmitryHordyna** [comment]
хорошо робота
